#!/usr/bin/env bash
set -euo pipefail

source "$HOME/dotfiles/bin/src/capture.bash"

out=
err=
rc=0

if command -v zig >/dev/null; then
	capture zig build test
else
	capture nix develop -c zig build test
fi

printf "%s\n" "$out"
if [ -n "$err" ]; then
	printf "%s\n" "$err" >&2
fi

exit "$rc"
